backend = "glx";
vsync = true;

shadow = false;
fading = false;

detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;

use-ewmh-active-win = true;
unredir-if-possible = true;

use-damage = true;

log-level = "warn";
